In [1]:
import numpy as np

In [19]:
x_data=np.array([2,4,6,8,10,12,14,16,18,20]).reshape(10,1)
t_data=np.array([0,0,0,0,0,0,1,1,1,1]).reshape(10,1)


In [26]:
x_data=np.array([[2,4],[4,11],[6,6],[8,5],[10,7],[12,16],[14,8],[16,3],[18,7]])
t_data=np.array([0,0,0,0,1,1,1,1,1]).reshape(9,1)


In [3]:
print(x_data)
print(t_data)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]


In [27]:
w=np.random.rand(2,1) #3X1 행렬
b=np.random.rand(1)
print(w,b)

[[0.76206988]
 [0.81064884]] [0.51618557]


In [5]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def loss_func(x,t):
    delta = 1e-7
    z=np.dot(x,w)+b
    y=sigmoid(z)
    return -np.sum(t*np.log(y+delta)+(1-t)*np.log(1-y+delta))
    

In [6]:
def numerical_derivative(f,x):
    delta_x=1e-4
    grad = np.zeros_like(x)
    
#     print("debug1. intial input variable = ", x)
#     print("debug2. initial input grad = ", grad)
#     print("======================================")
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
#         print("debug 3. idx= ", idx, ", x[idx]= ", x[idx])
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
#         print("debug4. grad[idx] = ", grad[idx])
#         print("debug5. grad = ", grad)
#         print("======================================")
        
        x[idx] = tmp_val
        it.iternext()
    return grad

In [14]:
def predict(x):
    z=np.dot(x,w)+b
    y=sigmoid(z)
    
    if y>0.5: 
        result = 1
    else:
        result =0
        
    return y, result

In [28]:
learning_rate = 1e-3
f= lambda x : loss_func(x_data, t_data)
for step in range(300001):
    w-= learning_rate*numerical_derivative(f,w)
    b-= learning_rate*numerical_derivative(f,b)
    if(step % 4000== 0):
          print("step = ",step, "error value = ", loss_func(x_data,t_data), "w =",w, ", b =",b)

step =  0 error value =  37.286129320555816 w = [[0.74222993]
 [0.78498586]] , b = [0.51221433]
step =  4000 error value =  2.266432698085236 w = [[ 0.4211786 ]
 [-0.08638247]] , b = [-2.63593587]
step =  8000 error value =  1.5923118762498056 w = [[ 0.53600257]
 [-0.02652659]] , b = [-4.25884163]
step =  12000 error value =  1.2821978108956757 w = [[0.62262189]
 [0.00870751]] , b = [-5.36468524]
step =  16000 error value =  1.1005115175614564 w = [[0.69267449]
 [0.03385233]] , b = [-6.2124055]
step =  20000 error value =  0.9788854235129167 w = [[0.75178567]
 [0.05388607]] , b = [-6.90642969]
step =  24000 error value =  0.8903253081028012 w = [[0.8030751 ]
 [0.07102844]] , b = [-7.49882219]
step =  28000 error value =  0.8220307952521354 w = [[0.84845474]
 [0.08643082]] , b = [-8.01912324]
step =  32000 error value =  0.7671391576589079 w = [[0.88918497]
 [0.10075038]] , b = [-8.48563242]
step =  36000 error value =  0.721630071588269 w = [[0.92614413]
 [0.11438639]] , b = [-8.910436

In [34]:
(real_val, logical_val)=predict([4,1])
print(real_val, logical_val)

[5.42807529e-06] 0


In [41]:
test_data=np.array([10,3])
predict(test_data)

(array([0.44649837]), 0)